-- AlterTable
ALTER TABLE `antiparasitaire` MODIFY `date` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `vaccin` MODIFY `date` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `vermifuge` MODIFY `date` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
